"""baseline schema

Revision ID: f5ae1166f775
Revises: 
Create Date: 2026-07-05 15:35:26.900610+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5ae1166f775'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appsetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appsetting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appsetting_key'), ['key'], unique=True)

    op.create_table('cronjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pipeline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('retry', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cronjob', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cronjob_name'), ['name'], unique=True)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('worker_pid', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_heartbeat_at'), ['heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_pipeline'), ['pipeline'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_status'), ['status'], unique=False)

    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sink_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sink_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('partition_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checkpointing', sa.Boolean(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('memory_limit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transforms', sa.JSON(), nullable=True),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('alerts', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_name'), ['name'], unique=True)

    op.create_table('pipelinerun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('rows_extracted', sa.Integer(), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipelinerun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipelinerun_pipeline_name'), ['pipeline_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipelinerun_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipelinerun_status'), ['status'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('pipelinerun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipelinerun_status'))
        batch_op.drop_index(batch_op.f('ix_pipelinerun_started_at'))
        batch_op.drop_index(batch_op.f('ix_pipelinerun_pipeline_name'))

    op.drop_table('pipelinerun')
    with op.batch_alter_table('pipeline', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_name'))

    op.drop_table('pipeline')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_status'))
        batch_op.drop_index(batch_op.f('ix_job_run_after'))
        batch_op.drop_index(batch_op.f('ix_job_pipeline'))
        batch_op.drop_index(batch_op.f('ix_job_heartbeat_at'))

    op.drop_table('job')
    with op.batch_alter_table('cronjob', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cronjob_name'))

    op.drop_table('cronjob')
    with op.batch_alter_table('appsetting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appsetting_key'))

    op.drop_table('appsetting')
    # ### end Alembic commands ###
