CREATE TABLE employees (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50),
    age INT,
    salary DECIMAL(10, 2)
);


insert into employees (name, age, salary) values ('Trumaine Hammerson', 26, 'Rupiah');
insert into employees (name, age, salary) values ('Sherman Keesman', 30, 'Krona');
insert into employees (name, age, salary) values ('Marthe Royal', 54, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Artie Brastead', 40, 'Dollar');
insert into employees (name, age, salary) values ('Yves Channon', 62, 'Ruble');
insert into employees (name, age, salary) values ('Skipper Tungate', 49, 'Euro');
insert into employees (name, age, salary) values ('Kingsley Rosenshine', 49, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Randie Palfree', 29, 'Euro');
insert into employees (name, age, salary) values ('Caria Dodding', 56, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Jocelyne Woodhall', 30, 'Krona');
insert into employees (name, age, salary) values ('Paco Pearde', 42, 'Euro');
insert into employees (name, age, salary) values ('Isidoro Alexis', 25, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Kassey Utting', 50, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Bastien Greenstreet', 53, 'Ruble');
insert into employees (name, age, salary) values ('Annette Ummfrey', 38, 'Tenge');
insert into employees (name, age, salary) values ('Kleon Saer', 62, 'Dollar');
insert into employees (name, age, salary) values ('Thekla Scarce', 63, 'Dollar');
insert into employees (name, age, salary) values ('Benedetta Emsley', 21, 'Euro');
insert into employees (name, age, salary) values ('Gabrila Burtonshaw', 34, 'Zloty');
insert into employees (name, age, salary) values ('Craggie Weiss', 51, 'Denar');
insert into employees (name, age, salary) values ('Caresa Brymham', 18, 'Tugrik');
insert into employees (name, age, salary) values ('Morly Ivanishev', 19, 'Euro');
insert into employees (name, age, salary) values ('Helene Bulleyn', 45, 'Ruble');
insert into employees (name, age, salary) values ('Heinrick Sanz', 45, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Jorge Stennett', 49, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Shoshana Covotti', 28, 'Yen');
insert into employees (name, age, salary) values ('Margot Skacel', 55, 'Euro');
insert into employees (name, age, salary) values ('Isabel Cogar', 62, 'Peso');
insert into employees (name, age, salary) values ('Nora Creavin', 34, 'Shilling');
insert into employees (name, age, salary) values ('Catharine Whal', 49, 'Euro');
insert into employees (name, age, salary) values ('Rosabella Huertas', 32, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Gorden Thridgould', 22, 'Euro');
insert into employees (name, age, salary) values ('Siegfried Rafferty', 36, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Whitney Penn', 31, 'Euro');
insert into employees (name, age, salary) values ('Nan De Cleen', 27, 'Real');
insert into employees (name, age, salary) values ('Delmore Bradder', 56, 'Dong');
insert into employees (name, age, salary) values ('Dan Kilbride', 29, 'Boliviano');
insert into employees (name, age, salary) values ('Clarie Dallon', 61, 'Krona');
insert into employees (name, age, salary) values ('Graig Beddie', 19, 'Rupiah');
insert into employees (name, age, salary) values ('Katee Montes', 45, 'Naira');
insert into employees (name, age, salary) values ('Lory MacCallion', 49, 'Euro');
insert into employees (name, age, salary) values ('Manda Kemmis', 37, 'Hryvnia');
insert into employees (name, age, salary) values ('Sydney Downage', 27, 'Peso');
insert into employees (name, age, salary) values ('Lindy McGrorty', 42, 'Ruble');
insert into employees (name, age, salary) values ('Teodor Burns', 41, 'Marka');
insert into employees (name, age, salary) values ('Devondra Jenteau', 50, 'Rupiah');
insert into employees (name, age, salary) values ('Law Jereatt', 43, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Pearla McNaught', 23, 'Peso');
insert into employees (name, age, salary) values ('Brianna Teather', 45, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Berry McAleese', 18, 'Krona');
insert into employees (name, age, salary) values ('Zeke Oakwell', 47, 'Rupiah');
insert into employees (name, age, salary) values ('Jehu Cheesman', 49, 'Euro');
insert into employees (name, age, salary) values ('Jacquenette Keays', 43, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Tricia Cham', 41, 'Cordoba');
insert into employees (name, age, salary) values ('Rich Engeham', 54, 'Koruna');
insert into employees (name, age, salary) values ('Darci Guenther', 48, 'Rupiah');
insert into employees (name, age, salary) values ('Stephanus Skeath', 47, 'Peso');
insert into employees (name, age, salary) values ('Deonne O''Nions', 35, 'Franc');
insert into employees (name, age, salary) values ('Kettie Fogg', 19, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Hannis Portigall', 25, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Yard Campa', 21, 'Euro');
insert into employees (name, age, salary) values ('Randie Blucher', 29, 'Rupiah');
insert into employees (name, age, salary) values ('Jordan Josifovic', 28, 'Peso');
insert into employees (name, age, salary) values ('Oralee Whiteland', 38, 'Dollar');
insert into employees (name, age, salary) values ('Ingemar Bletcher', 27, 'Euro');
insert into employees (name, age, salary) values ('Jada Skyppe', 26, 'Peso');
insert into employees (name, age, salary) values ('Maia Penzer', 32, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Corinna Wilfinger', 37, 'Euro');
insert into employees (name, age, salary) values ('Herbie Wichard', 52, 'Peso');
insert into employees (name, age, salary) values ('Etienne Leaming', 33, 'Baht');
insert into employees (name, age, salary) values ('Joshua Westney', 25, 'Rupiah');
insert into employees (name, age, salary) values ('Arney Sandbrook', 20, 'Zloty');
insert into employees (name, age, salary) values ('Marco Cordobes', 22, 'Rial');
insert into employees (name, age, salary) values ('Care Cowope', 26, 'Peso');
insert into employees (name, age, salary) values ('Jackelyn Shout', 62, 'Krona');
insert into employees (name, age, salary) values ('Tammara Hendriksen', 33, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Raymund Treagus', 57, 'Naira');
insert into employees (name, age, salary) values ('Birdie Marages', 19, 'Ruble');
insert into employees (name, age, salary) values ('Rebecca Stackbridge', 39, 'Kuna');
insert into employees (name, age, salary) values ('Bink Bowmen', 59, 'Peso');
insert into employees (name, age, salary) values ('Cloris Jeandon', 20, 'Rupiah');
insert into employees (name, age, salary) values ('Rani Aleksahkin', 50, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Cy Dunks', 28, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Billie Lydster', 49, 'Euro');
insert into employees (name, age, salary) values ('Hilton Tunesi', 48, 'Rupiah');
insert into employees (name, age, salary) values ('Lotta Outhwaite', 55, 'Hryvnia');
insert into employees (name, age, salary) values ('Bradan Stoving', 45, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Tani Keough', 38, 'Peso');
insert into employees (name, age, salary) values ('Ania Kivlehan', 33, 'Ruble');
insert into employees (name, age, salary) values ('Tommie McDill', 44, 'Euro');
insert into employees (name, age, salary) values ('Guillema Broadway', 61, 'Marka');
insert into employees (name, age, salary) values ('Willow Liptrod', 55, 'Peso');
insert into employees (name, age, salary) values ('Layney Okroy', 30, 'Kwanza');
insert into employees (name, age, salary) values ('Javier Shickle', 50, 'Rupiah');
insert into employees (name, age, salary) values ('Yoshiko Figger', 38, 'Rupiah');
insert into employees (name, age, salary) values ('Lucita Poyzer', 45, 'Peso');
insert into employees (name, age, salary) values ('Kaitlynn Pawlyn', 43, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Joell Acres', 41, 'Rand');
insert into employees (name, age, salary) values ('Lilah Canto', 49, 'Yuan Renminbi');
insert into employees (name, age, salary) values ('Melisande Cluet', 63, 'Cedi');

